# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dotnet release

on:
  release:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./Scd.ProjectX.Client/Scd.ProjectX.Client/Scd.ProjectX.Client.csproj
    - name: Build
      run: dotnet build ./Scd.ProjectX.Client/Scd.ProjectX.Client/Scd.ProjectX.Client.csproj --no-restore
    - name: Test
      run: dotnet test ./Scd.ProjectX.Client/Scd.ProjectX.Client.Tests/Scd.ProjectX.Client.Tests.csproj --verbosity normal
    - name: Build Nuget
      run: dotnet build ./Scd.ProjectX.Client/Scd.ProjectX.Client/Scd.ProjectX.Client.csproj -c Release --no-restore
    - name: Publish Nuget
      run: dotnet nuget push ./Scd.ProjectX.Client/Scd.ProjectX.Client/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
